services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
    - MINIO_ROOT_USER=${SECRET_USER}
    - MINIO_ROOT_PASSWORD=${SECRET_PASSWORD}
    labels:
      - homepage.group=Docker
      - homepage.name=MinIO
      - homepage.icon=minio.png
      - homepage.href=http://minio.${DOMAIN}
      - homepage.description=S3-like Backup Storage
      - traefik.enable=true
      - traefik.http.services.minio-minio.loadbalancer.server.port=9001
      - wud.tag.include=^RELEASE.\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}Z$
    networks:
    - default
    - web
    ports:
    - 9000:9000
    volumes:
    - ${PWD}/data:/data
networks:
  default:
    name: backup
    external: true
  web:
    external: true