copyright: © James Kelly 2024
dev_addr: '0.0.0.0:8080'
extra_css:
  - css/badges.css
  - css/expand.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tilde
repo_name: GitHub
repo_url: https://github.com/jamesdkelly88/db-lab
site_name: Db-Lab
theme:
  name: material
  features:
  - navigation.expand
  palette:
    scheme: slate