services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.7
    container_name: homepage
    labels:
      # - homepage.group=Web
      # - homepage.name=Homepage
      # - homepage.icon=homepage.png
      # - homepage.href=http://homepage.{$DOMAIN}
      # - homepage.description=This page
      - traefik.enable=true
      - wud.tag.include=^v\d+?.\d+?.\d+?$
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}

networks:
  default:
    name: docker
    external: true