services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.4.3
    container_name: homepage
    labels:
      - traefik.enable=true
      - wud.tag.include=^v\d+?.\d+?.\d+?$
    volumes:
      - ./config:/app/config
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      HOMEPAGE_ALLOWED_HOSTS: homepage.${DOMAIN}

networks:
  default:
    name: docker
    external: true