services:
  roach1:
    container_name: roach1
    hostname: roach1
    command: start --advertise-addr=roach1:26357 --http-addr=roach1:8080 --listen-addr=roach1:26357 --sql-addr=roach1:26257 --insecure --join=roach1:26357,roach2:26357,roach3:26357
    labels:
      - homepage.group=Web Interfaces
      - homepage.name=CockroachDB Cluster
      - homepage.href=http://roach1.${DOMAIN}
      - homepage.icon=https://upload.wikimedia.org/wikipedia/en/3/31/Cockroach_Labs_Logo.png
      - homepage.description=Relational (26258)
      - traefik.enable=true
      - traefik.http.services.roach1-cockroach.loadbalancer.server.port=8080
      - wud.tag.include=^v\d+?\.\d+?\.\d+?$
    image: cockroachdb/cockroach:v25.2.3
    ports:
    - 26258:26257
    restart: unless-stopped
    volumes:
    - roach1:/cockroach/cockroach-data
  roach2:
    container_name: roach2
    hostname: roach2
    command: start --advertise-addr=roach2:26357 --http-addr=roach2:8080 --listen-addr=roach2:26357 --sql-addr=roach2:26257 --insecure --join=roach1:26357,roach2:26357,roach3:26357
    labels:
      - wud.tag.include=^v\d+?\.\d+?\.\d+?$
    image: cockroachdb/cockroach:v25.2.3
    restart: unless-stopped
    volumes:
    - roach2:/cockroach/cockroach-data
  roach3:
    container_name: roach3
    hostname: roach3
    command: start --advertise-addr=roach3:26357 --http-addr=roach3:8080 --listen-addr=roach3:26357 --sql-addr=roach3:26257 --insecure --join=roach1:26357,roach2:26357,roach3:26357
    labels:
      - wud.tag.include=^v\d+?\.\d+?\.\d+?$
    image: cockroachdb/cockroach:v25.2.3
    restart: unless-stopped
    volumes:
    - roach3:/cockroach/cockroach-data

networks:
  default:
    name: web
    external: true
  cockroach:
    external: true
  
volumes:
  roach1:
  roach2:
  roach3:


# TODO: haproxy as load balancer
# TODO: automated setup
# docker exec roach1 cockroach --host=roach1:26357 init --insecure
# docker exec -it roach1 cockroach --host=roach1:26257 sql --insecure
# SET CLUSTER SETTING enterprise.license = 'xxxxxxxxxxxx';