services:
  postgres17:
    container_name: postgres17
    labels:
      - homepage.group=Relational
      - homepage.name=PostgreSQL 17
      - homepage.icon=postgres.png
      - homepage.description=PostgreSQL v17 (54327)
      - wud.tag.include=^17.\d{1,2}-alpine.+?$
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_PASSWORD: ${SECRET_PASSWORD}
    image: postgres:17.5-alpine3.20
    ports:
    - 54327:5432
    restart: unless-stopped
    volumes:
    - data:/var/lib/postgresql/data

networks:
  default:
    name: postgres
    external: true

volumes:
  data:
