services:
  pg-proxy:
    container_name: pg-proxy
    depends_on:
      - zookeeper
      - pg-primary
      - pg-secondary
      - pg-tertiary
    hostname: pg-proxy
    image: haproxy:3.1.1-alpine3.20
    labels:
      - homepage.group=Web Interfaces
      - homepage.name=HAProxy Stats
      - homepage.icon=haproxy.png
      - homepage.href=http://pg-proxy.${DOMAIN}
      - "homepage.description=For: PostgreSQL (HA)"
      - traefik.enable=true
      - traefik.http.services.pg-proxy-postgres-ha.loadbalancer.server.port=7000
      - wud.tag.include=^v\d+\.\d+\.\d+-alpine.+?$
    networks:
      - web
      - postgres
    ports:
      - 5433:5432
    volumes:
      - type: bind
        source: ./haproxy.cfg
        target: /usr/local/etc/haproxy/haproxy.cfg
    restart: unless-stopped
  pg-primary:
    container_name: pg-primary
    image: jamesdkelly88/postgres-patroni:17.5
    restart: unless-stopped
    hostname: pg-primary
    labels:
      - homepage.group=Databases
      - homepage.name=PostgreSQL (HA)
      - homepage.href=#
      - homepage.icon=postgres.png
      - homepage.description=Key-Value | Relational (5433)
      - wud.tag.include=^\d$
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      PATRONI_SUPERUSER_PASSWORD: ${SECRET_PASSWORD}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    expose:
      - 5432
      - 8008
    networks:
      - postgres
    volumes:
     - data1:/var/lib/postgresql/data
    command: patroni /postgres0.yml
  pg-secondary:
    container_name: pg-secondary
    image: jamesdkelly88/postgres-patroni:17.5
    restart: unless-stopped
    hostname: pg-secondary
    expose:
      - 5432
      - 8008
    volumes:
     - data2:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      PATRONI_SUPERUSER_PASSWORD: ${SECRET_PASSWORD}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    networks:
      - postgres
    command: patroni /postgres1.yml        
  pg-tertiary:
    container_name: pg-tertiary
    image: jamesdkelly88/postgres-patroni:17.5
    restart: unless-stopped
    hostname: pg-tertiary
    expose:
      - 5432
      - 8008
    volumes:
     - data3:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      PATRONI_SUPERUSER_PASSWORD: ${SECRET_PASSWORD}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    networks:
      - postgres
    command: patroni /postgres2.yml        
  zookeeper:
    container_name: zookeeper
    labels:
      - wud.tag.include=^\d+?.\d+?.\d+?$
    environment:
      ZOO_TICK_TIME: 2000
    image: zookeeper:3.9.3
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    external: true
  web:
    external: true

volumes:
  data1:
  data2:
  data3:
