services:
  postgres:
    container_name: postgres
    labels:
      - homepage.group=Databases
      - homepage.name=PostgreSQL 17 (Extensions)
      - homepage.href=#
      - homepage.icon=postgres.png
      - homepage.description=Graph | Key-Value | Relational | Spatial | Time-Series | Vector (5432)
      - wud.tag.include=^17.\d{1,2}$
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_PASSWORD: ${SECRET_PASSWORD}
    image: jamesdkelly88/postgres-full:17.5
    ports:
    - 5432:5432
    restart: unless-stopped
    volumes:
    - data:/var/lib/postgresql/data

networks:
  default:
    name: postgres
    external: true

volumes:
  data:
