services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:0.1.2
    container_name: dockerproxy
    labels:
      - homepage.group=Docker
      - homepage.name=Docker
      - homepage.icon=docker.png
      - homepage.description=Docker socket read-only proxy
      - wud.tag.include=^\d+?.\d+?.\d+?$
    environment:
      - CONTAINERS=1 # Allow access to viewing containers
      - SERVICES=0 # Allow access to viewing services (necessary when using Docker Swarm)
      - TASKS=0 # Allow access to viewing tasks (necessary when using Docker Swarm)
      - POST=0 # Disallow any POST operations (effectively read-only)
    ports:
      - 2375:2375
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Mounted as read-only
    restart: unless-stopped

networks:
  default:
    name: docker
    external: true