services:
  floci:
    image: floci/floci:1.5.23
    container_name: floci
    labels:
      - wud.tag.include=^\d+?.\d+?.\d+?$
    environment:
      FLOCI_HOSTNAME: floci
      FLOCI_DEFAULT_REGION: eu-west-1
      FLOCI_SERVICES_DOCKER_NETWORK: floci
      FLOCI_STORAGE_MODE: persistent
      FLOCI_STORAGE_PERSISTENT_PATH: /app/data
    networks:
    - default
    ports:
    - "4566:4566" #api
    - "6379-6399:6379-6399" #redis
    - "7001-7099:7001-7099" #rds
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - data:/app/data
networks:
  default:
    name: floci
    external: true
volumes:
  data: