---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- logo:
    icon: mdi-database

- datetime:
    format:
      dateStyle: short
      timeStyle: short

- resources:
    cpu: true
    memory: true
    disk: /
    cputemp: true
    uptime: true
    units: metric

- openmeteo:
    label: Sheffield
    latitude: 53.3811
    longitude: 1.466667
    timezone: Europe/London
    units: metric
    cache: 15
    format:
      maximumFractionDigits: 1

- search:
    provider: custom
    url: https://hub.docker.com/search?q=
    target: _blank
