services:
  puppygraph:
    image: puppygraph/puppygraph:0.94
    container_name: puppygraph
    environment:
     PUPPYGRAPH_PASSWORD: ${SECRET_PASSWORD}
    labels:
      - homepage.group=Web Interfaces
      - homepage.name=PuppyGraph
      - homepage.icon=https://avatars.githubusercontent.com/u/131501899?s=200&v=4
      - homepage.href=http://puppygraph.${DOMAIN}
      - "homepage.description=Graph | For: PostgreSQL (8182, 7688)"
      - traefik.enable=true
      - traefik.http.services.puppygraph-puppygraph.loadbalancer.server.port=8081
      - wud.tag.include=^\d+\.\d+$
    networks:
    - default
    - web
    ports:
    - 8182:8182
    - 7688:7687
    restart: unless-stopped
networks:
  default:
    name: postgres
    external: true
  web:
    external: true