services:
  postgres12:
    container_name: postgres12
    labels:
      - homepage.group=Databases
      - homepage.name=PostgreSQL 12
      - homepage.href=#
      - homepage.icon=postgres.png
      - homepage.description=Key-Value | Relational (54322)
      - wud.tag.include=^12.\d{1,2}-alpine.+?$
    environment:
      POSTGRES_PASSWORD: ${SECRET_PASSWORD}
    image: postgres:12.22-alpine3.20
    ports:
    - 54322:5432
    restart: unless-stopped
    volumes:
    - data:/var/lib/postgresql/data

networks:
  default:
    name: postgres
    external: true
      
volumes:
  data: